// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnNSTc2BojoaYHYOMnxypvZZoaWQ0OI80',
    appId: '1:466599615724:web:17ff0792d3a3753c6f59c9',
    messagingSenderId: '466599615724',
    projectId: 'flutter-iot-fffd8',
    authDomain: 'flutter-iot-fffd8.firebaseapp.com',
    storageBucket: 'flutter-iot-fffd8.appspot.com',
    measurementId: 'G-VXTPRWXBQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiEGvNAqDO62GmbuS7U2DD-dng63Xm0Sk',
    appId: '1:466599615724:android:cbd22a9e9b2bd6536f59c9',
    messagingSenderId: '466599615724',
    projectId: 'flutter-iot-fffd8',
    storageBucket: 'flutter-iot-fffd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Qm1-LHeq7ZR7VP-iLZsrw9FZwWPzhC8',
    appId: '1:466599615724:ios:5aef90d383cbd0c26f59c9',
    messagingSenderId: '466599615724',
    projectId: 'flutter-iot-fffd8',
    storageBucket: 'flutter-iot-fffd8.appspot.com',
    iosBundleId: 'com.m1ketesla.iotApp',
  );
}
